import {
    getFirestore,
    doc,
    getDoc,
    collection,
    getDocs,
    query,
    orderBy,
    startAfter,
    limit,
    QueryConstraint,
    DocumentSnapshot,
    where,
    WhereFilterOp,
    setDoc,
} from "firebase/firestore";

import { firestore as db } from "./fb.js";

type document = { __name__: string } & Record<string, any>;

// Cache all retreived documents
// This will help to prevent unnecessary reads from firestore
const docCache = new Map<string, Promise<document | null> | document | null>();

// Set of all documents that require a flush
const flushCache = new Set<string>();

/**
 * Generic method to get some document
 * @param id        The id of the document to retreive
 * @param autofill  If no document exists, return a fake document with only the __name__ field set.
 */
function _getDoc(id: string, autofill: false): Promise<document | null>;
function _getDoc(id: string, autofill?: true): Promise<document>;
function _getDoc(id: string, autofill = true): Promise<document | null> {
    if (id.startsWith("/")) id = id.substring(1); // Remove leading slash

    const cache = docCache.get(id);
    if (cache) {
        // Return cached document
        return new Promise(async (resolve) => {
            const doc = cache instanceof Promise ? await cache : cache;

            resolve(
                !doc
                    ? autofill
                        ? { __name__: id }
                        : null
                    : structuredClone(doc)
            );
        });
    }

    const promise = new Promise<document | null>(async (resolve) => {
        // Attempt to retreive document
        const docRef = doc(db, id);

        let snapshot;
        try {
            snapshot = await getDoc(docRef);
        } catch (err) {
            resolve(autofill ? { __name__: id } : null);
            docCache.set(id, null); // Save document (that doesn't exist)
            return;
        }

        if (!snapshot.exists()) {
            docCache.set(id, null);
            resolve(autofill ? { __name__: snapshot.id } : null);
            return;
        }

        const data = { ...snapshot.data(), __name__: snapshot.id };
        docCache.set(id, data); // Replace cached promise with the document
        resolve(structuredClone(data));
    });

    docCache.set(id, promise);
    return promise;
}

type setOptions = {
    flush?: boolean;
    merge?: boolean;

    collection?: string;
};

/**
 * Generic method to update some document.
 * @param id        The ID of the document to update. If not given, a new document ID will be autogenerated.
 * @param data      The new data to fill into the document.
 * @param options   How to update the data.
 */
function _setDoc(
    id: string | null,
    data: Record<string, any>,
    options?: setOptions
): Promise<document>;

/**
 * Generic method to update some document.
 * @param data      The full document to update.
 * @param options   How to update the data.
 */
function _setDoc(data: document, options?: setOptions): Promise<document>;
function _setDoc(
    param0: string | null | document,
    param1?: Record<string, any> | setOptions,
    param2?: setOptions
): Promise<document> {
    let newDoc: document;
    let options: setOptions | null;

    // Autogenerate new id
    if (param0 == null) {
        param0 = "";
        const chars =
            "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        for (let i = 0; i < 20; i++) {
            param0 += chars[Math.floor(Math.random() * chars.length)];
        }
    }

    // Id specified on its own
    if (typeof param0 == "string") {
        newDoc = {
            ...(param1 as Record<string, any>),
            __name__: param0,
        };
        options = param2 ?? null;
    }

    // Id given in document
    else {
        newDoc = param0;
        options = param1 ?? null;
    }

    let collection = options?.collection ?? "";
    if (collection.startsWith("/")) collection = collection.slice(1);
    if (collection && !collection.endsWith("/")) collection = collection + "/";

    let id = newDoc.__name__;
    if (id.startsWith("/")) id = id.slice(1);
    if (id.endsWith("/")) id = id.slice(0, -1);

    let fullPath = collection + id;

    return new Promise<document>(async (resolve) => {
        let cachedDoc = docCache.get(fullPath);

        // Wait for cached request to finish
        if (cachedDoc instanceof Promise) cachedDoc = await cachedDoc;

        // Default to flushing document through
        const flush = options?.flush ?? true;

        // No change to document, so no flush necessary
        if (
            !flushCache.has(fullPath) &&
            compare(cachedDoc as document, newDoc)
        ) {
            resolve(structuredClone(newDoc));
            return;
        }

        docCache.set(fullPath, newDoc);

        // Indicate that this document will need to be flushed later
        if (!flush) {
            flushCache.add(fullPath);
            resolve(structuredClone(newDoc));
            return;
        }

        // Remove __name__ field from document
        const newDocContents: Record<string, any> = { ...newDoc };
        delete newDocContents.__name__;

        // Update document
        await setDoc(doc(db, fullPath), newDocContents);

        resolve(structuredClone(newDoc));
    });
}

/**
 * Check if two objects are equal.
 * @param a
 * @param b
 */
function compare(a: any, b: any) {
    // Comparing primitive types
    if (!a || !b || typeof a != "object" || typeof b != "object")
        return a === b;

    // Different type of object
    if (Array.isArray(a) != Array.isArray(b)) return false;

    // Differently sized objects
    if (Object.keys(a).length != Object.keys(b).length) return false;

    for (const key in a) {
        if (!b.hasOwnProperty(key)) return false; // Non-matching key
        if (!compare(a[key], b[key])) return false; // Non-matching value
    }

    // Nothing didn't match, so objects must be identical!
    return true;
}

type colInfo = {
    docs: { doc: document; snapshot: DocumentSnapshot }[]; // Retreived documents
    fetch?: {
        size: number; // The number of documents being fetched
        promise: Promise<document[]>; // Resolves when the current fetch cycle is complete
    };
};

// Cache all retreived collections
// This will help to prevent unnecessary reads from firestore
const colCache = new Map<
    string,
    Map<
        string,
        Map<
            string,
            {
                forwards?: colInfo;
                reversed?: colInfo;
                all: boolean;
            }
        >
    >
>();

/**
 * Generic method to get all documents in some collection
 * @param col
 * @param pageInfo
 */
function _getDocs(
    col: string,
    pageInfo: {
        field?: string;
        prevId?: string;
        limit?: number;
        reversed?: boolean;
    } = {},
    filter: [field: string, operator: WhereFilterOp, value: any] | null = null
): Promise<document[]> {
    // Remove leading and trailing slashes
    if (col.startsWith("/")) col = col.substring(1);
    if (col.endsWith("/")) col = col.substring(0, col.length - 1);

    const fbField = pageInfo.field ?? "__name__";
    const fbLimit = pageInfo.limit ?? Infinity;
    const direction = pageInfo.reversed ?? false ? "reversed" : "forwards";
    const filterStr = JSON.stringify(filter);

    let cache = colCache.get(col)?.get(fbField)?.get(filterStr);
    let dirCache = cache?.[direction];
    if (!cache || !dirCache) {
        if (!colCache.has(col)) colCache.set(col, new Map());
        if (!colCache.get(col)!.has(fbField))
            colCache.get(col)!.set(fbField, new Map());
        if (!colCache.get(col)!.get(fbField)!.has(filterStr))
            colCache.get(col)!.get(fbField)!.set(filterStr, { all: false });
        if (
            !colCache
                .get(col)!
                .get(fbField)!
                .get(filterStr)!
                .hasOwnProperty(direction)
        )
            colCache.get(col)!.get(fbField)!.get(filterStr)![direction] = {
                docs: [],
            };
        cache = colCache.get(col)!.get(fbField)!.get(filterStr)!;
        dirCache = cache?.[direction]!;
    }

    let startIndex =
        pageInfo.prevId == null
            ? Infinity
            : dirCache.docs.findIndex(
                  ({ doc }) => doc.__name__ == pageInfo.prevId
              );

    // Invalid start index
    if (startIndex == -1) return Promise.resolve([]);
    if (startIndex == Infinity) startIndex = -1; // Useful for ordering later

    // All documents already retreived; Search local db for results
    if (cache.all) {
        return Promise.resolve(
            dirCache.docs
                .slice(startIndex + 1, startIndex + 1 + fbLimit)
                .map(({ doc }) => structuredClone(doc))
        );
    }

    // All documents requested already within internal storage
    if (dirCache.docs.length > startIndex + fbLimit) {
        return Promise.resolve(
            dirCache.docs
                .slice(startIndex + 1, startIndex + 1 + fbLimit)
                .map(({ doc }) => structuredClone(doc))
        );
    }

    // Currently waiting on some documents to fetch...
    if (dirCache.fetch) {
        // Wait for the current fetch to finish, then attempt to fetch again (or pull from local cahce)
        return dirCache.fetch!.promise.then(() =>
            _getDocs(col, pageInfo, filter)
        );
    }

    const promise = new Promise<document[]>(async (resolve) => {
        const fbCol = collection(db, col);

        const queryParams: QueryConstraint[] = [];
        if (filter) {
            queryParams.push(where(filter[0], filter[1], filter[2]));
        }
        if (dirCache.docs.length) {
            queryParams.push(
                startAfter(dirCache.docs[dirCache.docs.length - 1].snapshot)
            );
        }

        let docCount = Infinity;
        if (Number.isFinite(fbLimit) && fbLimit > 0) {
            docCount = startIndex + fbLimit - dirCache.docs.length + 1;
            queryParams.push(limit(docCount));
        }

        const snapshot = await getDocs(
            query(
                fbCol,
                orderBy(fbField, direction == "reversed" ? "desc" : "asc"),
                ...queryParams
            )
        );

        // All documents already gathered; This call was redundant...
        if (!cache.all) {
            // Update cache
            for (const doc of snapshot.docs) {
                const data = { ...doc.data(), __name__: doc.id };
                dirCache.docs.push({
                    doc: data,
                    snapshot: doc,
                });

                // Save document into doc cache as well
                const fullId = `${col}/${doc.id}`;
                if (!docCache.has(fullId))
                    docCache.set(fullId, { ...doc.data(), __name__: fullId });
            }
            delete dirCache.fetch;

            // Assume all documents have been gathered
            if (snapshot.docs.length != docCount) {
                cache.all = true;

                // Update documents in the other direction
                const revDir =
                    direction == "forwards" ? "reversed" : "forwards";
                cache[revDir] = { docs: dirCache.docs.toReversed() };
            }
        }

        resolve(
            dirCache.docs
                .slice(startIndex + 1, startIndex + 1 + fbLimit)
                .map((db) => structuredClone(db.doc))
        );
    });

    dirCache.fetch = {
        promise,
        size: fbLimit,
    };
    return promise;
}

/**
 * Dump cache, and force all documents to be refetched
 */
function _reload() {
    docCache.clear();
    colCache.clear();
    flushCache.clear();
}

export default {
    getDoc: _getDoc,
    getDocs: _getDocs,
    setDoc: _setDoc,

    reload: _reload,
};
